# Site settings
title: 经超的微博
email: jingchao920315@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  欢迎来到经超的博客.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jingchao920315.github.io/" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


 Social account
 #twitter:  username
 weibo:    蕊蕊撒拉嘿呦么么哒
 github:   https://github.com/jingchao920315
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
